# Mantiene la porta richiesta dal Cloud
server.port=${PORT:8080}

# Configurazione con le credenziali reali di PandaStack
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://f0bdacd2-b89b-4e38-b014-0358bd82cd0b.db.pandastack.ai:5432/malta?sslmode=require
spring.datasource.username=malta
spring.datasource.password=malta

# Configurazione Hibernate per PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configurazione Thymeleaf
spring.thymeleaf.cache=false

