# Usa la porta dinamica 3000 del Cloud (o la 8080 sul tuo PC)
server.port=${PORT:8080}

# Configurazione dinamica per PostgreSQL 16
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configurazione Hibernate ottimizzata per PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configurazione Thymeleaf
spring.thymeleaf.cache=false
