# Usa la porta dinamica 3000 del Cloud (o la 8080 sul tuo PC)
server.port=3000

# Configurazione dinamica per PostgreSQL 16
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.200.9.50:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configurazione Hibernate ottimizzata per PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configurazione Thymeleaf
spring.thymeleaf.cache=false
