server.port=${PORT:3000}
server.address=0.0.0.0

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:02d9a4f2-1ebe-439a-a4c4-97054e874895.db.pandastack.ai}:${DB_PORT:5432}/${DB_NAME:pandastack}?sslmode=require
spring.datasource.username=${DB_USER:pandastack}
spring.datasource.password=${DB_PASSWORD:C5gbmv9phGv0RPTta_oFHN-JY0SBCEyu}

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.forward-headers-strategy=framework




